name: Deploy Sorting Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '19.x'
      - run: npm install
      - run: npm run build
      - name: Commit built assets
        run: |
          git config --local user.email "achyutkneupane@gmail.com"
          git config --local user.name "Achyut Neupane"
          git checkout -B deploy
          git add -f public/
          git commit -m "Build front-end assets"
          git push -f origin deploy
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to sorting.achyut.com.np
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: 'cd /home/sambatsh/sorting.achyut.com.np && chmod +x ./deploy.sh && ./deploy.sh'
